name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package sonar:sonar --file pom.xml -Dsonar.host.url="https://sonarcloud.io" -Dsonar.organization="univ-smb-m1-isc-2019" -Dsonar.login=${SONAR_TOKEN:-''}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
